### ISSUE TITLE
may need to change repo to point to docker.io vs quay.io

### ISSUE THREAD

**Issue by tcskill** [cloud-native-toolkit/terraform-tools-sealed-secrets#21]
unable to pull images from quay.io repo, but changed to docker.io in the deployment manually and was able to.  this info seems to point to images being available from docker.io in the future for the sealec-secrets-controller.... changing deployment image to this worked: docker.io/bitnami/sealed-secrets-controller:v0.17.5

https://github.com/bitnami-labs/sealed-secrets/issues/822

**Comment by triceam** [comment]
All deployments to new clusters are broken until this gets resolved b/c the respository is gone at https://quay.io/repository/bitnami/sealed-secrets-controller

There are 2 possible solutions:

1. Point at the images on dockerhub: https://hub.docker.com/r/bitnami/sealed-secrets-controller/tags.  However, we will likely run into usage/rate limit issues
2. Mirror the images onto quay in our org, so we can pull from quay

In either case, we need to address this pretty quickly

**Comment by seansund** [comment]
> All deployments to new clusters are broken until this gets resolved b/c the respository is gone at https://quay.io/repository/bitnami/sealed-secrets-controller
> 
> There are 2 possible solutions:
> 
> 1. Point at the images on dockerhub: https://hub.docker.com/r/bitnami/sealed-secrets-controller/tags.  However, we will likely run into usage/rate limit issues
> 2. Mirror the images onto quay in our org, so we can pull from quay
> 
> In either case, we need to address this pretty quickly

For 1 - The rate limit issue with docker hub can be mitgated somewhat by adding a pull secret for docker.io to the deployment or the service account deploying kubeseal.
For 2 - We have a process (although it appears to be defunct due to a permission issue) in the tekton task repo - https://github.com/IBM/ibm-garage-tekton-tasks. `mapping.txt` defines the source and destination repo and the `mirror-images.yaml` workflow synchronizes the images on a daily schedule

**Comment by triceam** [comment]
from https://docs.docker.com/docker-hub/download-rate-limit/:
> Docker Hub limits the number of Docker image downloads (“pulls”) based on the account type of the user pulling the image. Pull rates limits are based on individual IP address. For anonymous users, the rate limit is set to 100 pulls per 6 hours per IP address. For [authenticated](https://docs.docker.com/docker-hub/download-rate-limit/#how-do-i-authenticate-pull-requests) users, it is 200 pulls per 6 hour period. There are no limits for users with a paid Docker subscription.

We can try the docker approach and see if we hit rate limits.   It's at least worth a shot.  Since it is IP-based, each cluster should have it's own limit.

**Comment by triceam** [comment]
It looks like we were pulling 0.17.1 from bitnami, but that version is not available on dockerhub, so I guess we go with the latest: [`bitnami/sealed-secrets-controller:v0.17.5`](https://hub.docker.com/r/bitnami/sealed-secrets-controller/tags).

**Comment by tcskill** [comment]
In my original note I used:  docker.io/bitnami/sealed-secrets-controller:v0.17.5 (manually changed the deployment) and it worked, started up and has handled several gitops deployments now without error

**Comment by triceam** [comment]
reopening b/c workflow failed in merge to main
